_target_: action_translation.ActionTranslatorSB3Policy

base_policy:
  _target_: stable_baselines3.PPO
  policy:
    _target_: stable_baselines3.common.policies.MlpPolicy
    net_arch: [64, 64]
    activation_fn: nn.ReLU
    ortho_init: False
  # Path to the trained base policy checkpoint
  checkpoint_path: /home/wph52/weird/dynamics/rl/runs/InvertedPendulum-v5_20250923_150900/models/best_model.zip

action_translator:
  _target_: action_translation.SimpleActionTranslator
  action_dim: 1
  obs_dim: 4
  # Path to the trained action translator checkpoint
  checkpoint_path: /home/wph52/weird/dynamics/datasets/pendulum/relabeled_actions/pendulum_integrable_dynamics_shift/action_translator_model.pth 





