name: "ant_flow_inverse_dynamics"
_target_: "dynamics.inverse.learned_inverse_dynamics.FlowInverseDynamics"
diffusion_step_embed_dim: 16
down_dims: [16, 32, 64]
num_inference_steps: 100
device: "cuda"
