_target_: generative_policies.inverse_dynamics.FlowInverseDynamics
name: ant_flow_id
action_dim: 8 
obs_dim: 107

diffusion_step_embed_dim: 32
down_dims: [32, 64, 128]
num_inference_steps: 10

# Path to the trained action translator checkpoint
checkpoint_path: null

