_target_: generative_policies.inverse_dynamics.MlpInverseDynamics
name: ant_mlp_id
action_dim: 8 
obs_dim: 107

net_arch: [64, 64, 64]

checkpoint_path: /home/wph52/weird/dynamics/datasets/ant/transitions/ant_5m_large/ant_mlp_id_20251009_140802_inverse_dynamics.pth

