_target_: generative_policies.inverse_dynamics.FlowInverseDynamics
name: pendulum_flow_id
action_dim: 1
obs_dim: 4

diffusion_step_embed_dim: 16
down_dims: [16, 32, 64]
num_inference_steps: 10

weight_decay: 1e-4

checkpoint_path: /home/wph52/weird/dynamics/datasets/pendulum/transitions/pendulum_integrable_large/pendulum_flow_id_20251009_003539_inverse_dynamics.pth