_target_: generative_policies.inverse_dynamics.FlowInverseDynamics
name: pendulum_flow_id
action_dim: 1
obs_dim: 4

diffusion_step_embed_dim: 32
down_dims: [32, 64, 128]
num_inference_steps: 10


checkpoint_path: /home/wph52/weird/dynamics/datasets/pendulum/transitions/pendulum_integrable/pendulum_flow_id_20251008_142909_inverse_dynamics.pth