_target_: inverse.learned_inverse_dynamics.FlowInverseDynamics
name: pendulum_flow_id
action_dim: 1
obs_dim: 4

diffusion_step_embed_dim: 16
down_dims: [16, 32]
num_inference_steps: 10


checkpoint_path: /home/wph52/weird/dynamics/datasets/pendulum/transitions/pendulum_integrable/pendulum_flow_id_20251008_142909_inverse_dynamics.pth