_target_: generative_policies.FlowPolicy
action_len: 16
action_dim: ${dataset.shape_meta.action.shape[0]}
obs_encoder:
  _target_: generative_policies.LowDimObservationEncoder
  shape_meta: ${dataset.shape_meta}
  num_frames: ${obs_num_frames}

noise_pred_net:
  _target_: generative_policies.UnetNoisePredictionNet
  input_dim: ${model.action_dim}
  global_cond_dim: 32  # 4 obs keys * 4 shape each * 2 frames
  diffusion_step_embed_dim: 256
num_train_steps: 100
num_inference_steps: 10
