_target_: generative_policies.FlowPolicy
action_len: 16
action_dim: ${dataset.shape_meta.action.shape[0]}
obs_encoder:
  _target_: generative_policies.LowDimObservationEncoder
  shape_meta: ${dataset.shape_meta}
  num_frames: ${obs_num_frames}

noise_pred_net:
  _target_: generative_policies.UnetNoisePredictionNet
  _partial_: True
  input_len: ${model.action_len}
  input_dim: ${model.action_dim}
  global_cond_dim: ???
  timestep_embed_dim: 256
  embed_dim: 768
  num_heads: 12
  mlp_ratio: 4
  qkv_bias: True
num_train_steps: 100
num_inference_steps: 10
