_target_: stable_baselines3.PPO
policy:
  _target_: stable_baselines3.common.policies.MlpPolicy
  net_arch: [64, 64]
  activation_fn: nn.ReLU
  ortho_init: False
# Path to the trained base policy checkpoint
checkpoint_path: /home/wph52/weird/dynamics/rl/runs/Ant-v5_20251002_211516/models/best_model.zip



