_target_: stable_baselines3.PPO
policy:
  _target_: stable_baselines3.common.policies.MlpPolicy
  net_arch: [64, 64]
  activation_fn: nn.ReLU
  ortho_init: False
# Path to the trained base policy checkpoint

# Previous one
#checkpoint_path: /home/wph52/weird/dynamics/rl/runs/AntHighFriction-v1_20251009_191821/models/best_model.zip


# New 10/13
checkpoint_path: /home/wph52/weird/dynamics/rl/runs/AntHighFriction-v1_20251012_214132/models/best_model.zip


