_target_: stable_baselines3.SAC
policy:
  _target_: stable_baselines3.common.policies.MultiInputPolicy


checkpoint_path: /home/wph52/weird/dynamics/rl/runs/Robosuite-Door-Panda_20251016_190434/models/best_model.zip