_target_: datasets.trajectory_dataset.make_trajectory_dataset
name: pendulum

# Dataset collection parameters
model_path: /home/wph52/weird/dynamics/rl/runs/InvertedPendulum-v5_20250923_150900/models/best_model.zip
env_id: InvertedPendulumIntegrable-v5
source_env_id: InvertedPendulumIntegrable-v5
buffer_path: /home/wph52/weird/dynamics/datasets/pendulum/sequence/pendulum_integrable_huge/buffer.zarr
env_kwargs: null
num_episodes: 1000
max_steps_per_episode: 1000
deterministic: false
seed: null
append: false
shape_meta:
  # acceptable types: rgb, low_dim
  obs:
    # lowdim
    "cart_position":
      shape: [1]
      type: low_dim
    "pole_angle":
      shape: [1]
      type: low_dim
    "cart_velocity":
      shape: [1]
      type: low_dim
    "pole_velocity":
      shape: [1]
      type: low_dim

  action:
    # 1(torque)
    shape: [1]

seq_len: ${num_frames}
history_len: ${obs_num_frames}
normalize_action: True
normalize_lowdim: True
val_ratio: 0.20