_target_: null
name: ant_original_high_friction

# Dataset collection parameters
model_path: /home/wph52/weird/dynamics/rl/runs/AntHighFriction-v1_20251009_191821/models/best_model.zip
env_id: AntHighFriction-v1
buffer_dir: /home/wph52/weird/dynamics/datasets/ant/sequence/ant_original_high_friction
env_kwargs: null
num_episodes: 10
max_steps_per_episode: 1000
deterministic: false
seed: null
append: false

shape_meta:
  # acceptable types: rgb, low_dim
  obs:
    "full_obs":
      shape: [107]
      type: low_dim
  action:
    shape: [8]

seq_len: ${num_frames}
history_len: ${obs_num_frames}
normalize_action: False
normalize_lowdim: False
val_ratio: 0.20