_target_: null
name: door_modphys

defaults:
  - source_policy: panda_door_modphys

env_id: Robosuite-HighFriction-Door-Panda
buffer_dir: /home/wph52/weird/dynamics/datasets/door/transitions/door_modphys
env_kwargs: null
num_episodes: 100
max_steps_per_episode: 50
deterministic: false
seed: null
append: false


seq_len: ${num_frames}
history_len: ${obs_num_frames}
normalize_action: True
normalize_lowdim: True
val_ratio: 0.20