_target_: null
name: pendulum_integrable_mlp_shift

# Dataset collection parameters
model_path: /home/wph52/weird/dynamics/rl/runs/InvertedPendulumIntegrableMLPShift-v5_20250929_222040/models/best_model.zip
env_id: InvertedPendulumIntegrableMLPShift-v5
buffer_dir: /home/wph52/weird/dynamics/datasets/pendulum/sequence/pendulum_integrable_mlp_shift
env_kwargs: null
num_episodes: 10
max_steps_per_episode: 1000
deterministic: false
seed: null
append: false

shape_meta:
  # acceptable types: rgb, low_dim
  obs:
    # lowdim
    "cart_position":
      shape: [1]
      type: low_dim
    "pole_angle":
      shape: [1]
      type: low_dim
    "cart_velocity":
      shape: [1]
      type: low_dim
    "pole_velocity":
      shape: [1]
      type: low_dim

  action:
    # 1(torque)
    shape: [1]

seq_len: ${num_frames}
history_len: ${obs_num_frames}
normalize_action: True
normalize_lowdim: True
val_ratio: 0.20