hydra:
  run:
    dir: /home/wph52/weird/dynamics/il/runs/${dataset.name}_${now:%Y%m%d_%H%M%S}

algo: ${hydra:runtime.choices.model}
exp_id: default
seed: 0
logdir: ${hydra:run.dir}
resume: False
use_amp: False
eval_task_name: ${dataset.name}
pretrain_checkpoint_path: null
wandb_mode: online

num_steps: 10000
eval_every: 100 # 10000
save_every: 100

batch_size: 64
num_frames: 18 # originally 19 for some reason
obs_num_frames: 2
clip_grad_norm: null

optimizer:
  lr: 1e-4
  weight_decay: 1e-6
  betas: [0.9, 0.999]
  eps: 1e-8

scheduler:
  name: "constant"