_target_: action_translation.FlowActionPriorTranslator
name: ant_flow
action_dim: 8 
obs_dim: 107

diffusion_step_embed_dim: 32
continuous_diffusion_step: False
down_dims: [32, 64]
num_train_steps: 100
num_inference_steps: 10
timeshift: 1.0

# Path to the trained action translator checkpoint
checkpoint_path: null

