#_target_: generative_policies.action_translation.FlowActionPriorConditionedTranslator
_target_: generative_policies.action_translation.FlowActionPriorConditionedTranslator
name: ant_flow_int_modphys
action_dim: 8 
obs_dim: 107

diffusion_step_embed_dim: 32
down_dims: [32, 64, 128]
num_inference_steps: 10

checkpoint_path: null