_target_: generative_policies.action_translation.FlowActionPriorTranslator
name: door_flow_og_modphys_prior
action_dim: 7
obs_dim: 57

diffusion_step_embed_dim: 32
down_dims: [32, 64, 128]
num_inference_steps: 10

checkpoint_path: /home/wph52/weird/dynamics/datasets/door/relabeled_actions/door_modphys/translator_door_flow_og_modphys_prior_20251019_123307.pth


