_target_: generative_policies.action_translation.FlowActionPriorConditionedTranslator
name: pendulum_flow
action_dim: 1 
obs_dim: 4

diffusion_step_embed_dim: 32
down_dims: [32, 64]
num_inference_steps: 10

# Path to the trained action translator checkpoint
#checkpoint_path: /home/wph52/weird/dynamics/datasets/pendulum/relabeled_actions/pendulum_integrable_dynamics_shift/pendulum_flow_20251008_053911_translator.pth
checkpoint_path: /home/wph52/weird/dynamics/datasets/pendulum/relabeled_actions/pendulum_integrable_dynamics_shift/pendulum_flow_20251009_145728_translator.pth


