_target_: generative_policies.action_translation.FlowActionPriorTranslator
name: pendulum_flow_modphys_prior
action_dim: 1 
obs_dim: 4

diffusion_step_embed_dim: 32
down_dims: [32, 64]
num_inference_steps: 10

weight_decay: 1e-4

# Target with 1.8 randn (100 traj x 100 steps)
checkpoint_path: /home/wph52/weird/dynamics/datasets/pendulum/relabeled_actions/pendulum_modphys_random/translator_pendulum_flow_modphys_prior_20251025_172720_best.pth
