_target_: generative_policies.action_translation.FlowActionPriorTranslator
name: pusher_flow_og_modphys_prior
action_dim: 7
obs_dim: 6

diffusion_step_embed_dim: 32
down_dims: [32, 64, 128]
num_inference_steps: 10

# weight_decay: 1e-4

# No WD
checkpoint_path: /home/wph52/weird/dynamics/datasets/pusher/relabeled_actions/pusher_modphys/pusher_flow_id_object_gripper/translator_pusher_flow_og_modphys_prior_20251026_134739.pth

# WD 1e-4
# checkpoint_path: /home/wph52/weird/dynamics/datasets/pusher/relabeled_actions/pusher_modphys/pusher_flow_id_object_gripper/translator_pusher_flow_og_modphys_prior_20251025_175622_best.pth
