_target_: generative_policies.action_translation.FlowActionPriorConditionedTranslator
name: pusher_flow_og_modphys_wd
action_dim: 7
obs_dim: 23

diffusion_step_embed_dim: 32
down_dims: [32, 64, 128]
num_inference_steps: 10

weight_decay: 1e-4

checkpoint_path: /home/wph52/weird/dynamics/datasets/pusher/relabeled_actions/pusher_modphys/pusher_flow_id/translator_pusher_flow_og_modphys_wd_20251025_125824_best.pth


