_target_: generative_policies.action_translation.FlowBC  
name: pusher_bc_modphys
action_dim: 7
obs_dim: 23

diffusion_step_embed_dim: 32
down_dims: [32, 64, 128]
num_inference_steps: 10

model_type: transformer

checkpoint_path: /home/wph52/weird/dynamics/datasets/pusher/relabeled_actions/pusher_modphys/pusher_flow_id/translator_pusher_bc_modphys_20251026_151710_best.pth